apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: cilium-ingress
spec:
  cidrs:
    - cidr: 192.1.1.68/29
  disabled: false
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: cilium
