---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Los_Angeles
  METALLB_LB_RANGE: 10.1.1.245-10.1.1.255
  METALLB_K8S_GATEWAY_ADDR: 10.1.1.255
  METALLB_INGRESS_ADDR: 10.1.1.245
